---
title: "problem_set_script"
author: "Wenxin Xu"
date: "3/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

PS1

Question 3 Bonferroni

group1 vs group4
```{r}
# t-statistic
t= -4.15

# p=2P(|T|≥t)
p=2*(1-pt(abs(t),df=136))

# p star
p_star=3*p

print(p)

print(p_star)
```


group2 vs group4
```{r}
# t-statistic
t= -2.415

# p=2P(|T|≥t)
p=2*(1-pt(abs(t),df=136))

# p star
p_star=3*p

print(p)

print(p_star)
```


group3 vs group4
```{r}
# t-statistic
t= -1.84

# p=2P(|T|≥t)
p=2*(1-pt(abs(t),df=136))

# p star
p_star=3*p

print(p)

print(p_star)
```



PS2

```{r}
# F critical value
qf(1-0.05,df1=1,df2=10-2)
```
```{r}
# p-value P(F≥28.52)
1-pf(28.52,1,10-2)
```


```{r}
# t_3,0.975
qt(1-0.5/2,df=5-2)
```

```{r}
# p=2×P(T≥0.09)
2*(1-pt(0.09,df=5-2))
```


problem set 3

```{r}
# critical value F_0.95 (6,106)
qf(0.95, df1=6, df2=106)
```

```{r}
# p value p=P(F≥14.67)
1-pf(14.67, df1=6, df2=106)
```


```{r}
# critical value for t_106,0.975
qt(1-0.05/2, df=106)
```



```{r}
# critical value for F_0.95 (3,106)
qf(1-0.05, df1=3, df2=106)
```
```{r}
# p value for P(F≥11.73)
1-pf(11.73, df1=3, df2=106)
```


PS 4 Logistic regression

```{r}
# p=P(Z≥2.20)
2*(1-pnorm(2.20))

```

```{r}
# p=P(Z≥0.09)
2*(1-pnorm(0.09))

```


PS 6 Survival analysis

```{r}
# P(χ^2≥12.45) log-rank test
1-pchisq(12.45, df=1)
```

```{r}
# p=2×P(Z≥2.754) Cox proportional hazards model
2*(1-pnorm(2.754))
```


